[package]
name = "vulkan-asyncqueue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.37.3"
image = "0.24.6"
log = "0.4.19"
tokio = { version = "1.28.2", features = ["full"] }
